kind: pipeline
type: docker
name: default

environment:
  CL_SOURCE_REGISTRY: /drone/src/
  COVERAGE: 1
  CIRCLECI: 1

steps:
- name: run
  image: fukamachi/sbcl:latest-alpine
  commands:
  - apk add git
  - ros install fukamachi/rove
  - ros install fukamachi/cl-coveralls
  - rove cl-drone-example.asd
  - coveralls report/
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
