kind: pipeline
type: docker
name: default

environment:
  CL_SOURCE_REGISTRY: /drone/src/
  COVERAGE: 1
  CIRCLECI: 1

steps:
- name: restore-cache-with-filesystem
  image: meltwater/drone-cache
  pull: true
  settings:
    backend: "filesystem"
    restore: true
    cache_key: "volume"
    archive_format: "gzip"
    # filesystem_cache_root: "/tmp/cache"
    mount:
      - 'tocache'
  volumes:
  - name: cache
    path: /tmp/cache

- name: run
  image: fukamachi/sbcl:latest-alpine
  commands:
  #- apk add git file
  #- ros install fukamachi/rove
  #- ros install fukamachi/cl-coveralls
  - ls -a
  - ls -a /root
  - ls -a /drone/src
  - if [ -f 'tocache/test.txt' ]; then cat tocache/test.txt; fi
  - mkdir tocache
  - echo "AAA" > tocache/test.txt
  #- rove cl-drone-example.asd
  #- coveralls report/
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token

- name: rebuild-cache-with-filesystem
  image: meltwater/drone-cache
  pull: true
  settings:
    backend: "filesystem"
    rebuild: true
    cache_key: "volume"
    archive_format: "gzip"
    # filesystem_cache_root: "/tmp/cache"
    mount:
      - 'tocache'
  volumes:
  - name: cache
    path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache
